# Generated by Django 4.2.13 on 2024-06-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_options_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'priority']},
        ),
    ]
