# Generated by Django 4.2.13 on 2024-06-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
